### ISSUE TITLE
Support ktor 2.0

### ISSUE THREAD

**Issue by yogurtearl** [plannigan/ktor-moshi#48]
in ktor 2.0 some of the package names have changed ([available thru the EAP](https://ktor.io/eap/))

ktor 1.x: 
```
io.ktor.features.ContentNegotiation
```

ktor 2.x: 
```
io.ktor.server.plugins.ContentNegotiation
```

**Comment by yogurtearl** [comment]
@plannigan would you accept a PR for this and do a release?

**Comment by plannigan** [comment]
Yes. I'd be happy to review PRs to this repo.

Sorry about not responding initially. I haven't anything with the side project that was using this for sometime, so it hasn't been top of mind.
