### ISSUE TITLE
Publish info about the Code Signing Key

### ISSUE THREAD

**Issue by yogurtearl** [plannigan/ktor-moshi#51]
A couple of questions related to verifying the signature on the artifacts for this library. 

- What public key can be use to verify the signature on the artifacts?
- What key server is the public key published to?
- What is the key-id for that key? 
- What email address is tied to the public key?  

(This would be needed to verify the signatures that are available on maven central) 
https://repo1.maven.org/maven2/com/hypercubetools/ktor-moshi-server/2.1.0/ktor-moshi-server-2.1.0.jar.asc

**Comment by plannigan** [comment]
Starting with [v3.0.0](https://github.com/plannigan/ktor-moshi/releases/tag/v3.0.0), releases are signed using [this key](https://keys.openpgp.org/search?q=182A78549C4E519D3F18C29ECCBCFD4FECCD8EE1) associated with my email (p.lannigan@gmail.com), the same email used in my commits. I have also start signing my commits with the same key.
